---
- name: Deploy the dockerfile
  hosts: node 
  become: yes
  tasks:
    - name: Run backend-service container
      docker_container:
        name: backend-service
        image: backend-service
        state: started
        restart_policy: always
        ports:
          - "8081:8081"

    - name: Run frontend-service container
      docker_container:
        name: frontend-service
        image: frontend-service
        state: started
        restart_policy: always
        ports:
          - "5000:5000"

