- hosts: node
  tasks:
    - name: Deploy to AWS
      docker_container:
        name: backend-service
        image: manishpandey123/backend-service
        state: started
        restart_policy: always
        ports:
          - "8081:8081"
<<<<<<< HEAD
    - name: Deploy to AWS
      docker_container:
        name: frontend-service
        image: manishpandey123/frontend-service
        state: started
        restart_policy: always
        ports:
          - "5000:5000"

=======
>>>>>>> 981bff3f4e148300c1e74fb8b17037732a36689c
