- hosts: node
  tasks:
    - name: Deploy to AWS
      docker_container:
        name: backend-service
        image: manishpandey123/backend-service
        state: started
        restart_policy: always
        ports:
          - "8081:8081"
