- hosts: localhost
  tasks:
    - name: Deploy to AWS
      docker_container:
        name: backend-service
        image: mp708514@gmail.com/backend-service
        state: started
        restart_policy: always
        ports:
          - "8081:8081"
    - name: Deploy to Azure
      docker_container:
        name: frontend-service
        image: mp708514@gmail.com/frontend-service
        state: started
        restart_policy: always
        ports:
          - "5000:5000"

